[project]
name = "cn2tw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "googletrans>=4.0.2",
    "opencc>=1.1.9",
    "pyinstaller>=6.12.0",
    "pyqt6>=6.8.1",
    "tqdm>=4.67.1",
]
